### ISSUE TITLE
文档内容错误

### ISSUE THREAD

**Issue by arcosx** [NiNiPing/Server#1]
被我发现了，
Authenticate
Additional URL : user/
Available methods :
POST : 使用登录凭证 code 获取用户 openid
POST Method:
参数说明
appid : 小程序唯一标识
**secret : 小程序的 app secret**
code : 登录时获取的 code
返回内容
status code : 200
data : {"openid": "123456789"}

应该改为
appsecret

**Comment by lcgooder** [comment]
哈哈哈改了，写的时候粗心大意，居然漏了app
